name = "revolutionary_teal_hare-4973"
version = "1.0.0"

[deployment]
permission = "public"
nodes = 1

[build]
dir = "build"
entry = "revolutionary_teal_hare-4973_debug.wasm"
command = "npm run build:debug"

[build_release]
dir = "build"
entry = "revolutionary_teal_hare-4973.wasm"
command = "npm run build:release"
